ci: clean up circle ci config (#164)
* ci: clean up circle ci config

- Use new CircleCI convenience images
  (https://circleci.com/docs/2.0/circleci-images/#next-gen-circleci-images)
- Use jobs with parameters
- Remove NPM_CONFIG_UNSAFE_PERM flag for running as root (was needed for
  node:* images, I believe)

* ci: use circleci "when" instead of bash for codecov

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,57 +1,25 @@
-version: 2
+version: 2.1
 
-test_env: &test_env
-  NPM_CONFIG_UNSAFE_PERM: true
-
-unit_tests: &unit_tests
-  steps:
-    - checkout
-    - run:
-        name: Setup environment variables
-        command: |
-          echo "export CIRCLE_NODE_VERSION=\$(node --version | grep -oE 'v[0-9]+')" >> $BASH_ENV
-          source $BASH_ENV
-    - run:
-        name: Log out node.js version
-        command: |
-          node --version
-          echo "CIRCLE_NODE_VERSION=${CIRCLE_NODE_VERSION}"
-    - run:
-        name: Install Root Dependencies
-        command: npm install --ignore-scripts
-    - run:
-        name: Boostrap dependencies
-        command: npx lerna bootstrap --no-ci
-    - run:
-        name: Unit tests
-        command: npm run test
-    - run:
-        name: Verify package.json dependencies of samples
-        command: |
-          set +eo pipefail
-          for sample_dir in $(realpath samples/*); do
-            pushd $sample_dir
-            npm ci
-
-            # verify dependencies are met without warnings or errors. Ignore
-            # "extraneous" messages, they are because of the local install
-            npm ls |& grep -v "extraneous" | grep "ERR!"
-            if [ $? -eq 0 ]; then
-              >&2 echo "Found dependency errors in $sample_dir package.json"
-              exit 1
-            else
-              exit 0
-            fi
-            popd
-          done
-    - run:
-        name: report coverage
-        command: if [ "${CIRCLE_NODE_VERSION}" = "v12" ]; then npm run codecov; fi
+executors:
+  node8:
+    docker:
+      - image: cimg/node:8.17
+  node10:
+    docker:
+      - image: cimg/node:10.22
+  node12:
+    docker:
+      - image: cimg/node:12.18
+  node13:
+    docker:
+      - image: cimg/node:13.14
+  node14:
+    docker:
+      - image: cimg/node:14.9
 
 jobs:
   lint:
-    docker:
-      - image: circleci/node:12
+    executor: node14
     steps:
       - checkout
       - run:
@@ -60,39 +28,61 @@ jobs:
       - run:
           name: Check code style and linting
           command: npm run lint
-  node8:
-    docker:
-      - image: circleci/node:8
-        environment: *test_env
-    <<: *unit_tests
-  node10:
-    docker:
-      - image: circleci/node:10
-        environment: *test_env
-    <<: *unit_tests
-  node12:
-    docker:
-      - image: circleci/node:12
-        environment: *test_env
-    <<: *unit_tests
-  node13:
-    docker:
-      - image: circleci/node:13
-        environment: *test_env
-    <<: *unit_tests
-  node14:
-    docker:
-      - image: circleci/node:14
-        environment: *test_env
-    <<: *unit_tests
+
+  unit_tests:
+    executor: node<< parameters.node_version >>
+    parameters:
+      node_version:
+        description: The node version to run the tests with
+        type: integer
+    steps:
+      - checkout
+      - run:
+          name: Log out node.js version
+          command: node --version
+      - run:
+          name: Install Root Dependencies
+          command: npm install --ignore-scripts
+      - run:
+          name: Boostrap dependencies
+          command: npx lerna bootstrap --no-ci
+      - run:
+          name: Unit tests
+          command: npm run test
+      - run:
+          name: Verify package.json dependencies of samples
+          command: |
+            set +eo pipefail
+            for sample_dir in $(realpath samples/*); do
+              pushd $sample_dir
+              npm ci
+
+              # verify dependencies are met without warnings or errors. Ignore
+              # "extraneous" messages, they are because of the local install
+              npm ls |& grep -v "extraneous" | grep "ERR!"
+              if [ $? -eq 0 ]; then
+                >&2 echo "Found dependency errors in $sample_dir package.json"
+                exit 1
+              else
+                exit 0
+              fi
+              popd
+            done
+      - when:
+          condition:
+            equal: [ << parameters.node_version >>, 14 ]
+          steps:
+            - run:
+                name: report coverage
+                command: npm run codecov
 
 workflows:
   version: 2
   build:
     jobs:
       - lint
-      - node8
-      - node10
-      - node12
-      - node13
-      - node14
+      - unit_tests:
+          name: node<< matrix.node_version >>
+          matrix:
+            parameters:
+              node_version: [8, 10, 12, 13, 14]
